### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Ktlo/Decimal#1]
1. Непонятен этот тест: 
```
assertEquals(Decimal.parseDecimal("4726"),
                Decimal.parseDecimal("4725.4825").round());
```
Почему 4725.4825 округляется в большую сторону? Это явно так вами и задумывалось (судя по коду округления), но можете привести ссылку на правила, которыми вы руководствовались?

2. Ваш класс вроде как иммутабельный везде, кроме одного места в методе `sub` , где вы временно меняете знак аргумента. Это убивает одно из больших преимуществ иммутабельности: такой объект в многопоточном приложении больше нельзя разделять между потоками без синхронизации. Раз вы делаете класс, который выглядит как иммутабельный, то лучше сделать его иммутабельным до конца (можно объявить все поля как `final` чтобы компилятор проверил это на этапе компиляции, разве что с полем `realLength` придётся немного повозиться)

**Comment by Ktlo** [comment]
1. Тест, как и метод round() исправил. Не знаю, почему я решил, что округление нужно было делать так, но, когда я писал функцию, я был уверен, что всё делаю верно.
2. Исправил метод, теперь все поля ```final```.
